
export const Colors ={
    primaryColor:{
        black:"#000000", 
    },
    secondaryColor:{
        blue:"#0078F6", 
    },
    whiteColor:{
      white:"#FFFFFF"  
    },
    accent:{
        lightBlack:"#00000066"
    },
    loginInputTextColor:{
        lighGrey:"#A9B2BE"
    },
    lineColor:{
        color:"#84939F"
    },
    cardBackGroundColor:{
        color:"#F7F7F8"
    },
    activeStudiesBlueText:{
        blue:"#0D7DF4"
    },
    infoScreenColors:{
        headerColor:"#9e9e9e",
        discription:"#000000"
    },
    captureVideoColor:{
        blue:"#11B8F5"
    }
}